CREATE DATABASE IF NOT EXISTS all_in_market CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE all_in_market;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  shop VARCHAR(120) NOT NULL DEFAULT '',
  phone VARCHAR(30) NOT NULL UNIQUE,
  email VARCHAR(160) NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  shop_type VARCHAR(80) NOT NULL DEFAULT '',
  status ENUM('active','banned') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS zones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  prefix CHAR(2) NOT NULL UNIQUE,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(160) NOT NULL DEFAULT '',
  color ENUM('violet','orange','green','blue') NOT NULL DEFAULT 'violet',
  price_day DECIMAL(10,2) NOT NULL DEFAULT 0,
  price_month DECIMAL(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stalls (
  id INT AUTO_INCREMENT PRIMARY KEY,
  zone_id INT NOT NULL,
  code VARCHAR(10) NOT NULL UNIQUE,
  is_open TINYINT(1) NOT NULL DEFAULT 1,
  price_day DECIMAL(10,2) NULL,
  FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NULL UNIQUE,
  user_id INT NOT NULL,
  stall_id INT NOT NULL,
  date_start DATE NOT NULL,
  date_end DATE NOT NULL,
  addons VARCHAR(160) NOT NULL DEFAULT '',
  days INT NOT NULL DEFAULT 1,
  stall_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  addons_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  status ENUM('awaiting_payment','pending','paid','rejected','cancelled') NOT NULL DEFAULT 'awaiting_payment',
  expires_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (stall_id) REFERENCES stalls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refunds (
  id INT AUTO_INCREMENT PRIMARY KEY,
  booking_id INT NOT NULL,
  reason VARCHAR(200) NOT NULL DEFAULT '',
  refund_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL DEFAULT '',
  phone VARCHAR(30) NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS addons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(200) NOT NULL DEFAULT '',
  price_day DECIMAL(10,2) NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS booking_addons (
  booking_id INT NOT NULL,
  addon_id INT NOT NULL,
  price_day DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (booking_id, addon_id),
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  FOREIGN KEY (addon_id) REFERENCES addons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS settings (
  k VARCHAR(60) PRIMARY KEY,
  v VARCHAR(255) NOT NULL DEFAULT ''
);
